version: '3'

services:
    nginx:
        image: nginx:1.16-alpine
        restart: unless-stopped
        container_name: blog-nginx
        working_dir: /app
        env_file:
            - ./.env
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - internal
        extra_hosts:
            - "blog.local:192.168.240.1"
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        restart: unless-stopped
        container_name: blog-php-fpm
        extra_hosts:
            - "blog.local:192.168.240.1"
        environment:
            XDEBUG_CONFIG: "client_host=192.168.240.1"
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - mysql
        env_file:
            - .env
        volumes:
            - ./app:/app
        networks:
            - internal
    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        container_name: blog-php-cli
        env_file:
            - .env
        volumes:
            - ./app:/app
            - composer:/root/.composer/cache
        depends_on:
            - mysql
        networks:
            - internal
    node:
        build:
            context: ./docker
            dockerfile: node.docker
        container_name: blog-node
        env_file:
            - ./.env
        volumes:
            - ./app:/app
        working_dir: /app
        networks:
            - internal

    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: blog-mysql
        tty: true
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        networks:
            - internal

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: blog-phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - internal

volumes:
  composer:
  dbdata:

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.240.0/28
