openapi: 3.0.0
info:
  title: 'API documentation for blog example.'
  description: 'Implementation of Swagger with in Laravel'
  contact:
    email: sergmoro1@ya.ru
  license:
    name: MIT
    url: 'https://mit-license.org/'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
    description: 'Blog API Server'
paths:
  /api/images:
    put:
      tags:
        - Images
      summary: 'Update image'
      description: 'Update existing image'
      operationId: updateImage
      parameters:
        -
          name: id
          in: query
          description: 'Image ID'
          required: true
          schema:
            type: integer
            format: int32
      requestBody: {  }
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Image updated.' }
                type: object
        '403':
          description: 'Wrong parameters'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'false' }
                  message: { type: string, example: 'Only the ''position'' and ''addons'' fields can be updated for images.' }
                type: object
        '404':
          description: 'Entity not found'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'false' }
                  message: { type: string, example: 'Not found.' }
                type: object
    post:
      tags:
        - Images
      summary: 'Save image'
      description: 'Save just uploaded image'
      operationId: createImage
      requestBody:
        required: true
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Image saved.' }
                type: object
  '/api/images/{id}':
    delete:
      tags:
        - Images
      summary: 'Delete image'
      description: 'Delete image by ID'
      operationId: deleteImage
      parameters:
        -
          name: id
          in: query
          description: 'Image ID'
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Image deleted.' }
                type: object
  /api/posts:
    get:
      tags:
        - Posts
      summary: 'Get list of posts'
      description: 'Returns list of posts'
      operationId: indexPost
      parameters:
        -
          name: search
          in: query
          description: 'search string to filter by'
          required: false
          schema:
            type: string
        -
          name: offset
          in: query
          description: 'offset from the beginning of the dataset'
          required: false
          schema:
            type: integer
            format: int32
        -
          name: limit
          in: query
          description: 'maximum number of results to return'
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    put:
      tags:
        - Posts
      summary: 'Update post'
      description: 'Update existing post'
      operationId: updatePost
      parameters:
        -
          name: id
          in: query
          description: 'Post ID'
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostOnly'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Post updated.' }
                type: object
    post:
      tags:
        - Posts
      summary: 'Create post'
      description: 'Create new post'
      operationId: createPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostOnly'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Post created.' }
                type: object
  '/api/posts/{id}':
    get:
      tags:
        - Posts
      summary: 'Get post'
      description: 'Get post by ID'
      operationId: getPost
      parameters:
        -
          name: id
          in: query
          description: 'Post ID'
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    delete:
      tags:
        - Posts
      summary: 'Delete post'
      description: 'Delete post by ID'
      operationId: deletePost
      parameters:
        -
          name: id
          in: query
          description: 'Post ID'
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Post deleted.' }
                type: object
  /api/tags:
    get:
      tags:
        - Tags
      summary: 'Get list of tags'
      description: 'Returns list of tags'
      operationId: indexTag
      parameters:
        -
          name: search
          in: query
          description: 'search string'
          required: false
          schema:
            type: string
        -
          name: limit
          in: query
          description: 'maximum number of results to return'
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
    put:
      tags:
        - Tags
      summary: 'Update tag'
      description: 'Update existing tag'
      operationId: updateTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagOnly'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Tag updated.' }
                type: object
    post:
      tags:
        - Tags
      summary: 'Create tag'
      description: 'Create new tag'
      operationId: createTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagOnly'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Tag created.' }
                type: object
  '/api/tags/{id}':
    get:
      tags:
        - Tags
      summary: 'Get tag'
      description: 'Get tag by ID'
      operationId: getTag
      parameters:
        -
          name: id
          in: query
          description: 'Tag ID'
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
    delete:
      tags:
        - Tags
      summary: 'Delete tag'
      description: 'Delete tag by ID'
      operationId: deleteTag
      parameters:
        -
          name: id
          in: query
          description: 'Tag ID'
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'Tag deleted.' }
                type: object
  /api/users:
    get:
      tags:
        - Users
      summary: 'Get list of users'
      description: 'Returns list of users'
      operationId: indexUser
      parameters:
        -
          name: search
          in: query
          description: 'search string'
          required: false
          schema:
            type: string
        -
          name: limit
          in: query
          description: 'maximum number of results to return'
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    put:
      tags:
        - Users
      summary: 'Update user'
      description: 'Update existing user'
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserOnly'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'User updated.' }
                type: object
    post:
      tags:
        - Users
      summary: 'Create user'
      description: 'Create new user'
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserOnly'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'User created.' }
                type: object
  '/api/users/{id}':
    get:
      tags:
        - Users
      summary: 'Get user'
      description: 'Get user by ID'
      operationId: getUser
      parameters:
        -
          name: id
          in: query
          description: 'User ID'
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
        - Users
      summary: 'Delete user'
      description: 'Delete user by ID'
      operationId: deleteUser
      parameters:
        -
          name: id
          in: query
          description: 'User ID'
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  success: { type: boolean, example: 'true' }
                  message: { type: string, example: 'User deleted.' }
                type: object
components:
  schemas:
    PostOnly:
      properties:
        id:
          type: integer
          example: 1
        status:
          type: string
          enum:
            - draft
            - published
            - archived
          example: draft
        title:
          type: string
          example: 'Genius title'
        excerpt:
          type: string
          example: 'Excerpt of Content'
        Content:
          type: string
          example: 'Long Content'
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
    Post:
      properties:
        id:
          type: integer
          example: 1
        status:
          type: string
          enum:
            - draft
            - published
            - archived
          example: draft
        title:
          type: string
          example: 'Genius title'
        excerpt:
          type: string
          example: 'Excerpt of Content'
        Content:
          type: string
          example: 'Long Content'
        Tags:
          type: array
          items:
            $ref: '#/components/schemas/TagOnly'
        Tags_to_str:
          type: string
          example: 'news, sport'
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
    TagOnly:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: php
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
    Tag:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: php
        Posts:
          type: array
          items:
            $ref: '#/components/schemas/PostOnly'
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
    UserOnly:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Alex
        email:
          type: email
          example: alex@mail.ru
        email_verified_at:
          type: string
          format: date-time
          example: '2022-07-04T17:29:00+0300'
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
    User:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Alex
        email:
          type: string
          example: alex@mail.ru
        email_verified_at:
          type: string
          format: date-time
          example: '2022-07-04T17:29:00+0300'
        Posts:
          type: array
          items:
            $ref: '#/components/schemas/PostOnly'
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
  securitySchemes:
    basicAuth:
      type: http
      description: 'Basic authentication by email & password.'
      name: Authorization
      in: header
      scheme: basic
