openapi: 3.0.0
info:
  title: 'API documentation for blog example.'
  description: 'Implementation of Swagger with in Laravel'
  contact:
    email: sergmoro1@ya.ru
  license:
    name: MIT
    url: 'https://mit-license.org/'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
    description: 'Blog API Server'
paths:
  /api/index:
    get:
      tags:
        - Posts
      summary: 'Get list of postss'
      description: 'Returns list of posts'
      operationId: getPostList
      parameters:
        -
          name: 'tags[]'
          in: query
          description: 'tag to filter by'
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        -
          name: limit
          in: query
          description: 'maximum number of results to return'
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
components:
  schemas:
    Post:
      properties:
        id:
          type: integer
          example: 1
        status:
          type: string
          enum:
            - draft
            - published
            - archived
          example: draft
        title:
          type: string
          example: 'Genius title'
        excerpt:
          type: string
          example: 'Excerpt of Content'
        Content:
          type: string
          example: 'Long Content'
        Tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
    Tag:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: php
        created_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
        updated_at:
          type: string
          format: date-time
          example: '2022-07-04T16:31:00+0300'
      type: object
