openapi: 3.0.0
info:
  title: 'API documentation for blog example.'
  description: 'Implementation of Swagger with in Laravel'
  contact:
    email: sergmoro1@ya.ru
  license:
    name: MIT
    url: 'https://mit-license.org/'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
    description: 'Demo API Server'
paths:
  /api/index:
    get:
      tags:
        - Posts
      summary: 'Get list of postss'
      description: 'Returns list of posts'
      operationId: getPostList
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post-resource.yaml'
